filter:
    paths: [src/*]
    excluded_paths: [assets/*, bin/*, config/*, tests/*, vendor/*]

checks:
    php:
        code_rating: true

tools:
    external_code_coverage:
        timeout: 900
        runs: 2
    php_code_coverage: true
    php_loc:
        enabled: true
        excluded_dirs: [assets, tests, vendor]
    php_mess_detector:
        enabled: true
        filter:
            paths: ['src/*']
    php_pdepend:
        enabled: true
        excluded_dirs: [assets, tests, vendor]
    sensiolabs_security_checker: true