ArchInspec:
  - policy: siblings
  - deny: PhpDA
    rationale: Do not use PhpDA anywhere, except where allowed to reduce coupling.

ArchInspec\Application:
  - allow: ArchInspec\Inspector

ArchInspec\Command:
  - allow: Symfony\Component\Console

ArchInspec\Inspector:
  - allow: ArchInspec

ArchInspec\Node:
  - allow: ArchInspec\Policy

ArchInspec\Policy:
  - allow: ArchInspec\Node\NodeInterface


ArchInspec\Application\ArchInspec:
  - allow: PhpDA
    rationale: We'll bind to PhpDA inside ArchInspec
ArchInspec\PhpDA\ReferenceValidator:
  - allow: PhpDA\Reference\ValidatorInterface
    rationale: This implements the reference validator to be used by PhpDA