ArchInspec:
  - policy: siblings

ArchInspec\Application:
  - allow: ArchInspec\Inspector

ArchInspec\Command:
  - allow: Symfony\Component\Console

ArchInspec\Inspector:
  - allow: ArchInspec

ArchInspec\Node:
  - allow: ArchInspec\Policy

ArchInspec\Policy:
  - allow: ArchInspec\Node\NodeInterface