ArchInspec\Command:
  - allow: Symfony\Component\Console

ArchInspec\Node:
  - allow: ArchInspec\Policy

ArchInspec\Policy:
  - deny: ArchInspec\Node
    reason: The node must not use the policy at all costs! This was decided in #43